export default [
  {
    id: 0,
    title: "제목1",
    content: "내용1",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "안녕",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 1,
    title: "제목2",
    content: "내용2",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "여기는",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 2,
    title: "제목3",
    content: "내용3",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "몰라",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 3,
    title: "제목4",
    content: "내용4",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "일단",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 4,
    title: "제목5",
    content: "내용5",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "디자인",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 5,
    title: "제목6",
    content: "내용6",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "구상중",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 6,
    title: "제목7",
    content: "내용7",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "디자인",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 7,
    title: "제목8",
    content: "내용8",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "어려워",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
  {
    id: 8,
    title: "제목9",
    content: "내용9",
    likes: 0,
    commentCount: 0,
    comment: [],
    views: 0,
    category: "죽어버려",
    image:
      "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&w=1200",
  },
];
